### ISSUE TITLE
Allow more control of the inner `conda build`, `conda convert` and `anaconda upload` commands

### ISSUE THREAD

**Issue by atteggiani** [uibcdf/action-build-and-upload-conda-packages#14]
## Overview
Currently, there is no control over the `conda build`, `conda convert` and `anaconda upload` commands within the action.

[`conda build`](https://docs.conda.io/projects/conda-build/en/stable/resources/commands/conda-build.html), [`conda convert`](https://docs.conda.io/projects/conda-build/en/stable/resources/commands/conda-convert.html) and `anaconda upload` commands have optional command line arguments that cannot fully be covered within the inputs of this action, but that users might want to use in their "conda-build-upload" workflows.

## Examples
1. If a user wanted to specify Anaconda channels for the `conda build` command:
   ``` 
   conda build ... -c my_channel -c my_other_channel
   ```
   This is especially important when the conda build performs tests and needs to install the built package, which might need dependencies from the specified Anaconda channels.

2. If a user wants to use channels and enforce a specific package format (for example `.tar.bz2`) within the conda build, they could use:
   ```
   conda build ... -c my_channel --package-format 1
   ```
   This is currently not possible.

3. If a user wants to force the conversion of a package even when it contains compiled C extensions, they could use:
   ```
   conda convert ... --force
   ```
   This is currently not possible.

## Solution
A practical solution, present also in other GitHub actions that interact with specific executables like this one, is to add action inputs for each of the executables additional command-line arguments.

My proposal, is to add 3 input arguments which serve similar purposes, one for each of the three executables (`conda build`, `conda convert`, `anaconda upload`). These inputs are strings and should contain the additional input arguments for each of the action executables:

- `conda_build_args`
   Additional arguments for the `conda build` command
- `conda_convert_args`
   Additional arguments for the `conda convert` command
- `anaconda_upload_args`
   Additional arguments for the `anaconda upload` command
  
This way, the [examples](#examples) above could be made possible through:

#### Example 1
   ```yml
   use: uibcdf/action-build-and-upload-conda-packages
   with:
       ...
       conda_build_args:  -c my_channel -c my_other_channel
   ```

#### Example 2
   ```yml
   use: uibcdf/action-build-and-upload-conda-packages
   with:
       ...
       conda_build_args:  -c my_channel --package-format 1
   ```

#### Example 3
   ```yml
   use: uibcdf/action-build-and-upload-conda-packages
   with:
       ...
       conda_convert_args:  --force
   ```

### Handle potential duplicate options
Since some of the action inputs already implement specific optional arguments for different commands, if a user carelessly uses the action this might result in having the same option multiple times (which for specific options returns an error).
This is, for example, the case with the `python-version` input. If, together with this input, the user uses the `--python` optional argument within the new `conda_build_args` input (regardless of the values specified), this would result in an error. An example of how this would look like inside a GitHub workflow is shown below:
```yml
use: uibcdf/action-build-and-upload-conda-packages
with:
    ...
    python-version: 3.10 
    conda_build_args:  --python 3.9
```

Since the conda errors are not very explicative in this case, I think the best way is to handle these cases manually.
The easiest way would be to throw a more descriptive error, in case the user specifies an option in one of the `conda_***_args` that would already be specified with another action input (Along with making it clear in the README).
This way, the user would know what is raising the error and what they need to modify (either remove the option from the `conda_***_args` or remove the specific input).

Another point related to this, would be to think about removing some of the inputs that, with the addition of the new `conda_***_args` inputs would be redundant.
In my opinion, the only reason to still keep some separate inputs that would have the same effect as adding an optional argument through `conda_***_args`, would be to make that option "clearer" and more visible and easily accesible to the user, without them needing to carefully read the `conda` manual.
The currently available inputs that I think would be redundant and could be removed are:
- `python-version` (Another reason to remove this, or at least make it NOT required, is that `conda build` as a default would build the package with the python version present in its _base_ environment, which makes it not required).

In general, I think the addition of such control would highly increase the usability of this action.
