### ISSUE TITLE
How do you test the action?

### ISSUE THREAD

**Issue by dprada** [uibcdf/action-build-and-upload-conda-packages#26]
@atteggiani, how do you test the action in development?

I was playing with [`act`](https://github.com/nektos/act) to run the action locally. But I didn't manage to have it running properly... and to be honest I didn't have a good first impression of its use. I don't know... should I give a second chance to `act`?

I do the following:
- A new branch named `xxx` is created to make the tests and changes.
- The call to this action in my library YYY is targetted to the new branch:
```
- name: Build and upload the conda packages
        uses: uibcdf/action-build-and-upload-conda-packages@xxx
        with:
          meta_yaml_dir: devtools/conda-build
          python-version: ${{ matrix.python-version }}
          mambabuild: false
          user: uibcdf
          label: main
          conda_build_args: --package-format tar.bz2
          platform_linux-64: true
          platform_osx-64: true
          platform_osx-arm64: true
          platform_win-64: true
          token: ${{ secrets.ANACONDA_UIBCDF_TOKEN }}
```
- The action of YYY is triggered manually until the code in the branch `xxx` is clean.

Do you know other approaches to this?
How do you manually test the action?
Is there something like unit tests for GitHub Actions?
Should we open a new repository with a dummy Python library to test nightly that the action is working with different input arguments?
