### ISSUE TITLE
Action silently failing

### ISSUE THREAD

**Issue by bschroeter** [uibcdf/action-build-and-upload-conda-packages#29]
Hey there, I'm not sure if this is an "us" problem or an Action problem, but we have a number of our repositories silently failing on the conda upload portion of this action:

See:
https://github.com/CABLE-LSM/meorg_client/actions/runs/13190315035/job/37000419361#step:4:1420

The action returns green across the board, but no package is uploaded to anaconda.

The token and user ID used are valid.

There is nothing particularly sophisticated about the workflow - it was developed by lifting the examples from the docs.

```yaml
name: Conda Publish

on:
  release:
    types: [released]

jobs:
  conda_deployment:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: '3.9'
          environment-file: .conda/build_env.yaml
          auto-update-conda: false
          auto-activate-base: false
          show-channel-urls: true
      - name: Build and upload the conda packages
        uses: uibcdf/action-build-and-upload-conda-packages@v1.4.0
        with:
          python-version: '3.9'
          meta_yaml_dir: .conda
          user: ${{ secrets.ANACONDA_USER }}
          label: main
          token: ${{ secrets.ANACONDA_TOKEN }}
```

Please feel free to point out anything that I've misconfigured in the action - any assistance whatsoever is greatly appreciated. In the meantime we may need to revert to a non-action interactive publishing mechanism.

Thanks in advance!

Ben
