### ISSUE TITLE
How to configure it ?

### ISSUE THREAD

**Issue by benoit-cty** [uibcdf/action-build-and-upload-conda-packages#5]
Hello, I try to use your action script (thanks for it) but it did not work:

Here is my config https://github.com/mlco2/codecarbon/blob/master/.github/workflows/python-publish.yml#L61
```
      - name: Build and upload the conda packages
        uses: uibcdf/action-build-and-upload-conda-packages@v1.3.0
        with:
          meta_yaml_dir: .conda
          python-version: ${{ matrix.python-version }} # Values previously defined in `matrix`
          platform_linux-64: true
          platform_osx-64: true
          platform_win-64: true
          user: codecarbon
          label: auto
          token: ${{ secrets.ANACONDA_TOKEN }} # Replace with the right name of your secret
```

And the error:
https://github.com/mlco2/codecarbon/actions/runs/9220140010/job/25366550770#step:4:159
```
Building conda package for host platform
  conda build . --no-anaconda-upload --output-folder /tmp/compilation-xyCuDAjuQL --python 3.11
  usage: conda [-h] [-v] [--no-plugins] [-V] COMMAND ...
  conda: error: argument COMMAND: invalid choice: 'build' (choose from 'activate', 'deactivate', 'clean', 'compare', 'config', 'create', 'env', 'export', 'info', 'init', 'install', 'list', 'notices', 'package', 'remove', 'uninstall', 'rename', 'run', 'search', 'update', 'upgrade', 'content-trust', 'doctor', 'repoquery')
```

Any idea what's wrong ?

**Comment by RaulPPelaez** [comment]
Make sure the conda-build package is installed in the environment. The error is telling you it is not.

**Comment by benoit-cty** [comment]
Thanks, sorry I supposed that your action was taking care of that. So we have to use it with `- uses: conda-incubator/setup-miniconda@v3` for exemple. I will try it out.

**Comment by RaulPPelaez** [comment]
It can, but in your workflow you are failing to provide setup-miniconda with the environment file:
https://github.com/mlco2/codecarbon/blob/dd1e35897704657701fb343e882f9b65934a7215/.github/workflows/python-publish.yml#L53-L59
See from the README here:
```yaml
      - name: Conda environment creation and activation
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
          environment-file: devtools/conda-envs/build_env.yaml    # Path to the build conda environment
          auto-update-conda: false
          auto-activate-base: false
          show-channel-urls: true
```
build_env.yaml lists conda-build
